harden the scripts and update the script docs

diff --git a/cluster-start b/cluster-start
--- a/cluster-start
+++ b/cluster-start
@@ -6,31 +6,29 @@
 # N is the node number. The Akka port number is set to 255N, N is the node number.
 
 usage() {
-  echo "Usage: $0 nodes - Number of cluster nodes, number must be between 1-9" ; exit 1
+  echo "Usage: $0 nodes - Number of cluster nodes, number must be 1 through 9." ; exit 1
 }
-
-[ $# -eq 0 ] && usage
-
-nodes=$1
-jarFilename=$(find target -name *allinone.jar*)
-
-if [[ $nodes =~ ^[1-9]$ ]] ; then
-  echo -n "Starting $nodes cluster node" ; if [[ $nodes -gt 1 ]] ; then echo "s" ; else echo "" ; fi
-else
-  echo "Number of cluster nodes $nodes is invalid"
-  usage
-fi
 
 startNode() {
   node=$1
-  port="255"$node
-  export akka_management_http_port="855"$node
-  echo "Run node $1 on port $port, management port $akka_management_http_port"
-  java -jar $jarFilename $port &> /tmp/$(basename $PWD)-$node.log &
+  $scriptPath/node-start $node
 }
 
 startNodes() {
   for i in $(seq $1) ; do startNode $i ; done
 }
+
+[ $# -eq 0 ] && usage
+
+nodes=$1
+
+if [[ $nodes =~ ^[1-9]$ ]] ; then
+  echo -n "Starting $nodes cluster node" ; if [[ $nodes -gt 1 ]] ; then echo "s" ; else echo "" ; fi
+else
+  echo "Number of cluster nodes $nodes is invalid. The number of nodes must be 1 through 9."
+  usage
+fi
+
+scriptPath=$(dirname $0)
 
 startNodes $nodes
diff --git a/node-start b/node-start
--- a/node-start
+++ b/node-start
@@ -6,25 +6,26 @@
 # N is the node number. The Akka port number is set to 255N, N is the node number.
 
 usage() {
-  echo "Usage: $0 node - Start cluster node, node number must be between 1-9" ; exit 1
+  echo "Usage: $0 node - Start cluster node, node number must 1 through 9." ; exit 1
 }
 
 [ $# -eq 0 ] && usage
 
 node=$1
-jarFilename=$(find target -name *allinone.jar*)
+scriptPath=$(dirname $0)
+jarFilename=$(find $scriptPath/target -name *allinone.jar*)
 
 startNode() {
   node=$1
   port="255"$node
   export akka_management_http_port="855"$node
   echo "Start node $1 on port $port, management port $akka_management_http_port"
-  java -jar $jarFilename $port &> /tmp/$(basename $PWD)-$node.log &
+  java -jar $jarFilename $port &> /tmp/$(basename $scriptPath)-$node.log &
 }
 
 if [[ $node =~ ^[1-9]$ ]] ; then
   startNode $node
 else
-  echo "Cluster node number $node is invalid"
+  echo "Cluster node number $node is invalid. The node number must be 1 through 9."
   usage
 fi
diff --git a/node-stop b/node-stop
--- a/node-stop
+++ b/node-stop
@@ -3,24 +3,25 @@
 # Use this script to stop one Akka cluster node. The command line parameter must be from 1 to 9.
 
 usage() {
-  echo "Usage: $0 node - Stop cluster node, node number must be between 1-9" ; exit 1
+  echo "Usage: $0 node - Stop cluster node, node number must be 1 through 9." ; exit 1
+}
+
+stopNode() {
+  node=$1
+  port="255"$node
+  echo "Stop node $1 on port $port"
+  pkill -f "$(basename $jarFilename) $port"
 }
 
 [ $# -eq 0 ] && usage
 
 node=$1
-jarFilename=$(find target -name *allinone.jar*)
-
-startNode() {
-  node=$1
-  port="255"$node
-  echo "Stop node $1 on port $port"
-  pkill -f "$jarFilename $port"
-}
+scriptPath=$(dirname $0)
+jarFilename=$(find $scriptPath/target -name *allinone.jar*)
 
 if [[ $node =~ ^[1-9]$ ]] ; then
-  startNode $node
+  stopNode $node
 else
-  echo "Cluster node number $node is invalid"
+  echo "Cluster node number $node is invalid. The node number must be 1 through 9."
   usage
 fi
diff --git a/node-tail b/node-tail
--- a/node-tail
+++ b/node-tail
@@ -3,23 +3,24 @@
 # Use this script to tail a specific cluster node log file.
 
 usage() {
-  echo "Usage: $0 node - Tail cluster node number, between 1-9" ; exit 1
+  echo "Usage: $0 node - Tail cluster node number 1 through 9." ; exit 1
 }
 
 [ $# -eq 0 ] && usage
 
 node=$1
-jarFilename=$(find target -name *allinone.jar)
+scriptPath=$(dirname $0)
+jarFilename=$(find $scriptPath/target -name *allinone.jar)
 
 tailNode() {
   node=$1
   port="255"$node
-  tail -f /tmp/$(basename $PWD)-$node.log
+  tail -f /tmp/$(basename $scriptPath)-$node.log
 }
 
 if [[ $node =~ ^[1-9]$ ]] ; then
   tailNode $node
 else
-  echo "Cluster node number $node is invalid"
+  echo "Cluster node number $node is invalid. The node number must be 1 through 9."
   usage
 fi
